### PR TITLE
Enable debug and sched-ext patch on LTO for F41 in order to enable sched-ext support

### PR DESCRIPTION
**Pull request by andersrh**
The Fedora 42 version of dwarves package has been added to the dev repo for F41.

This should make it possible to enable debug.

### CODE REVIEW

**Review by 1Naim — APPROVED** [review]
This builds! Great work. You can go ahead and merge this after you've reverted customver to 1 and build it in the copr.

**Comment by andersrh** [comment]
> This builds! Great work. You can go ahead and merge this after you've reverted customver to 1 and build it in the copr.

I forgot to review the %if which disables the sched-ext patch on fedora 41, so it was only the debug which got enabled in the first build. Made a new test build where this has been fixed.

**Comment by 1Naim** [comment]
> > This builds! Great work. You can go ahead and merge this after you've reverted customver to 1 and build it in the copr.
> 
> I forgot to remove the %if which disables the sched-ext patch on fedora 41, so it was only the debug which got enabled in the first build. Made a new test build where this has been fixed.

Well it doesn't really matter if sched-ext is patched or not. As long as a debug-enabled kernel builds, scx kernel should build too.

**Comment by andersrh** [comment]
> > > This builds! Great work. You can go ahead and merge this after you've reverted customver to 1 and build it in the copr.
> > 
> > 
> > I forgot to remove the %if which disables the sched-ext patch on fedora 41, so it was only the debug which got enabled in the first build. Made a new test build where this has been fixed.
> 
> Well it doesn't really matter if sched-ext is patched or not. As long as a debug-enabled kernel builds, scx kernel should build too.

as far as i know the sched-ext patch needs to be applied in the kernel for the support to be there. When I tested it in my F41 VM scx-scheds didn't work.

**Comment by 1Naim** [comment]
> > > > This builds! Great work. You can go ahead and merge this after you've reverted customver to 1 and build it in the copr.
> > > 
> > > 
> > > I forgot to remove the %if which disables the sched-ext patch on fedora 41, so it was only the debug which got enabled in the first build. Made a new test build where this has been fixed.
> > 
> > 
> > Well it doesn't really matter if sched-ext is patched or not. As long as a debug-enabled kernel builds, scx kernel should build too.
> 
> as far as i know the sched-ext patch needs to be applied in the kernel for the support to be there. When I tested it in my F41 VM scx-scheds didn't work.

Yes, but what's broken is BTF in pahole, not scx itself.

**Comment by andersrh** [comment]
> Yes, but what's broken is BTF in pahole, not scx itself.

true. Will merge it now then :-)

**Pull request merged**
